"""Low-level AMQP 1.0 wire protocol: type codec, frames, performatives, messages, SASL.

This package is the lowest layer of the client and knows nothing about
connections, sessions or links; it only turns AMQP values, performatives and
frames into bytes and back.
"""

from __future__ import annotations

from .delivery_state import (
    Accepted,
    DeliveryState,
    Error,
    Modified,
    Received,
    Rejected,
    Released,
    decode_delivery_state,
)
from .encoding import (
    Array,
    Decoder,
    Described,
    Long,
    Symbol,
    Timestamp,
    decode_described_list,
    decode_value,
    encode_described_list,
    encode_value,
)
from .frames import (
    EMPTY_FRAME,
    FRAME_HEADER_SIZE,
    FRAME_TYPE_AMQP,
    FRAME_TYPE_SASL,
    FrameBody,
    build_frame,
    decode_frame_body,
    read_frame,
    read_protocol_header,
    write_frame,
    write_protocol_header,
)
from .message import (
    AmqpSequence,
    AmqpValue,
    ApplicationProperties,
    Data,
    DeliveryAnnotations,
    Footer,
    Header,
    Message,
    MessageAnnotations,
    Properties,
)
from .performatives import (
    EXPIRY_POLICY_LINK_DETACH,
    EXPIRY_POLICY_SESSION_END,
    RCV_SETTLE_MODE_FIRST,
    SND_SETTLE_MODE_SETTLED,
    SND_SETTLE_MODE_UNSETTLED,
    TERMINUS_DURABILITY_NONE,
    Attach,
    Begin,
    Close,
    Detach,
    Disposition,
    End,
    Flow,
    Open,
    Performative,
    Source,
    Target,
    Transfer,
    decode_performative,
    decode_performative_with_payload,
)
from .sasl import (
    AMQP_PROTOCOL_HEADER,
    AMQP_SASL_HEADER,
    MECHANISM_ANONYMOUS,
    MECHANISM_EXTERNAL,
    MECHANISM_PLAIN,
    SaslChallenge,
    SaslFrame,
    SaslInit,
    SaslMechanisms,
    SaslOutcome,
    SaslResponse,
    build_plain_initial_response,
    decode_sasl_frame,
)

__all__ = [
    "AMQP_PROTOCOL_HEADER",
    "AMQP_SASL_HEADER",
    "Accepted",
    "AmqpSequence",
    "AmqpValue",
    "ApplicationProperties",
    "Array",
    "Attach",
    "Begin",
    "Close",
    "Data",
    "Decoder",
    "DeliveryAnnotations",
    "DeliveryState",
    "Described",
    "Detach",
    "Disposition",
    "EMPTY_FRAME",
    "EXPIRY_POLICY_LINK_DETACH",
    "EXPIRY_POLICY_SESSION_END",
    "End",
    "Error",
    "FRAME_HEADER_SIZE",
    "FRAME_TYPE_AMQP",
    "FRAME_TYPE_SASL",
    "Flow",
    "Footer",
    "FrameBody",
    "Header",
    "Long",
    "MECHANISM_ANONYMOUS",
    "MECHANISM_EXTERNAL",
    "MECHANISM_PLAIN",
    "Message",
    "MessageAnnotations",
    "Modified",
    "Open",
    "Performative",
    "Properties",
    "RCV_SETTLE_MODE_FIRST",
    "Received",
    "Rejected",
    "Released",
    "SND_SETTLE_MODE_SETTLED",
    "SND_SETTLE_MODE_UNSETTLED",
    "TERMINUS_DURABILITY_NONE",
    "SaslChallenge",
    "SaslFrame",
    "SaslInit",
    "SaslMechanisms",
    "SaslOutcome",
    "SaslResponse",
    "Source",
    "Symbol",
    "Target",
    "Timestamp",
    "Transfer",
    "build_frame",
    "build_plain_initial_response",
    "decode_delivery_state",
    "decode_described_list",
    "decode_frame_body",
    "decode_performative",
    "decode_performative_with_payload",
    "decode_sasl_frame",
    "decode_value",
    "encode_described_list",
    "encode_value",
    "read_frame",
    "read_protocol_header",
    "write_frame",
    "write_protocol_header",
]
