name: Test against a RabbitMQ broker

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: rabbitmq_tls:latest
          outputs: type=docker,dest=/tmp/rabbitmq_tls.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rabbitmq_tls
          path: /tmp/rabbitmq_tls.tar
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: rabbitmq_tls
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/rabbitmq_tls.tar
          docker image ls -a
          docker run -d --rm --name rabbitmq-stream-client-test \
          -p 5552:5552 -p 5672:5672 -p 5671:5671 -p 5551:5551 -p 15672:15672 \
          -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_stream advertised_host localhost" \
          rabbitmq_tls
      - name: wait for running
        run: |
          docker exec rabbitmq-stream-client-test /bin/bash -c 'ps -aux'
          docker exec rabbitmq-stream-client-test /bin/bash -c 'sleep 10'
          docker exec rabbitmq-stream-client-test /bin/bash -c 'rabbitmqctl status'
          docker exec rabbitmq-stream-client-test /bin/bash -c 'rabbitmqctl wait --pid 1 --timeout 70'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: poetry install
        run: poetry install --no-root
      - name: isort check-only
        run: poetry run isort --skip rabbitmq_amqp_python_client/qpid --check-only .
      - name: black check
        run: poetry run black --check .
      - name: flake8
        run: poetry run flake8 --exclude=venv,local_tests,docs/examples,rabbitmq_amqp_python_client/qpid --max-line-length=120 --ignore=E203,W503
      - name: mypy
        run: | 
          poetry run mypy --exclude=rabbitmq_amqp_python_client/qpid .
      - name: poetry run pytest
        run: poetry run pytest