name: Test against a RabbitMQ broker

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start RabbitMQ
        id: start-rabbitmq
        run: ${{ github.workspace }}/.ci/ubuntu/gha-setup.sh
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: false

      - name: poetry install
        run: poetry install --no-root
      - name: isort check-only
        run: poetry run isort --skip rabbitmq_amqp_python_client/qpid --check-only .
      - name: black check
        run: poetry run black --check .
      - name: flake8
        run: poetry run flake8 --exclude=venv,local_tests,docs/examples,rabbitmq_amqp_python_client/qpid --max-line-length=120 --ignore=E203,W503
      - name: mypy
        run: | 
          poetry run mypy --exclude=rabbitmq_amqp_python_client/qpid .
      - name: poetry run pytest
        run: poetry run pytest