name: Test against a RabbitMQ broker

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    services:
      rabbitmq-server:
        image: rabbitmq:4.0.3-management
        ports:
          - 5672:5672
          - 15672:15672
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: false
      - name: Enable RabbitMQ Plugins
        run: docker exec ${{ job.services.rabbitmq-server.id }} rabbitmq-plugins enable rabbitmq_stream rabbitmq_stream_management rabbitmq_amqp1_0
      - name: poetry install
        run: poetry install --no-root
      - name: isort check-only
        run: poetry run isort --skip rabbitmq_amqp_python_client/qpid --check-only .
      - name: black check
        run: poetry run black --check .
      - name: flake8
        run: poetry run flake8 --exclude=venv,local_tests,docs/examples,rabbitmq_amqp_python_client/qpid --max-line-length=120 --ignore=E203,W503
      - name: mypy
        run: | 
          poetry run mypy --exclude=rabbitmq_amqp_python_client/qpid .
      - name: poetry run pytest
        run: poetry run pytest