name: publish-release

on:
  release:
    types:
      - released

jobs:
  call-publish-pypi:
    permissions:
      id-token: write
    uses: ./.github/workflows/publish-pypi.yaml
    with:
      pypi_repository_url: https://upload.pypi.org/legacy/
    secrets:
      pypi_api_login: __token__
      pypi_api_password: ${{ secrets.PYPI_TOKEN }}